// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-g4EH3CupBuWsFPp-V3e2Iu-F7rXCqE',
    appId: '1:241117876949:android:9e332d8cd7e1f7d358885c',
    messagingSenderId: '241117876949',
    projectId: 'whatapps-mess',
    databaseURL: 'https://whatapps-mess-default-rtdb.firebaseio.com',
    storageBucket: 'whatapps-mess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzW5_3YKteGyZT2JNvbKF_pY87z-8lWI',
    appId: '1:241117876949:ios:f3866b3929364d4258885c',
    messagingSenderId: '241117876949',
    projectId: 'whatapps-mess',
    databaseURL: 'https://whatapps-mess-default-rtdb.firebaseio.com',
    storageBucket: 'whatapps-mess.appspot.com',
    iosClientId: '241117876949-ab2opdpvet99e6apvl5bp20kvbopluam.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
